version: "3.9"

services:
  # ===== NATS =====
  nats1:
    image: nats:latest
    container_name: nats1
    ports:
      - "4223:4222"  # porta NATS para host
      - "8223:8222"  # porta Web para host
    command: >
      --server_name nats1
      --cluster_name pbl-cluster
      --cluster nats://0.0.0.0:6222
      --cluster_advertise nats1:6222
      --routes nats://nats2:6222,nats://nats3:6222
    networks:
      - pbl-network

  nats2:
    image: nats:latest
    container_name: nats2
    ports:
      - "4224:4222"
      - "8224:8222"
    command: >
      --server_name nats2
      --cluster_name pbl-cluster
      --cluster nats://0.0.0.0:6222
      --cluster_advertise nats2:6222
      --routes nats://nats1:6222,nats://nats3:6222
    networks:
      - pbl-network

  nats3:
    image: nats:latest
    container_name: nats3
    ports:
      - "4225:4222"
      - "8225:8222"
    command: >
      --server_name nats3
      --cluster_name pbl-cluster
      --cluster nats://0.0.0.0:6222
      --cluster_advertise nats3:6222
      --routes nats://nats1:6222,nats://nats2:6222
    networks:
      - pbl-network

  # ===== Servidores =====
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server1
    ports:
      - "8001:8001"
    environment:
      - ID=1
      - PORT=8001
      - PEERS=2=http://server2:8002,3=http://server3:8003
      - NATS_URL=nats://nats1:4222  # conecta ao NATS1 dentro da rede Docker
      - RAFT_ADVERTISE_ADDR=server1:8001
    networks:
      - pbl-network
    depends_on:
      - nats1

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server2
    ports:
      - "8002:8002"
    environment:
      - ID=2
      - PORT=8002
      - PEERS=1=http://server1:8001,3=http://server3:8003
      - NATS_URL=nats://nats2:4222
      - RAFT_ADVERTISE_ADDR=server2:8002
    networks:
      - pbl-network
    depends_on:
      - nats2

  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server3
    ports:
      - "8003:8003"
    environment:
      - ID=3
      - PORT=8003
      - PEERS=1=http://server1:8001,2=http://server2:8002
      - NATS_URL=nats://nats3:4222
      - RAFT_ADVERTISE_ADDR=server3:8003
    networks:
      - pbl-network
    depends_on:
      - nats3

networks:
  pbl-network:
    driver: bridge
