version: "3.9"

services:
  server1:
    build: .
    container_name: server1
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - PEERS=http://server2:8002,http://server3:8003

  server2:
    build: .
    container_name: server2
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - PEERS=http://server1:8001,http://server3:8003

  server3:
    build: .
    container_name: server3
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - PEERS=http://server1:8001,http://server2:8002
